config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

   delete '/cart_items/destroy_all', to: 'public/cart_items#destroy_all'

  scope module: :public do
    get '/homes/about', to: 'homes#about'
    resources :items
    get '/customers/check', to: 'customers#check'
    patch '/customers/check', to: 'customers#withdraw'
    resources :customers
    resources :addresses
    resources :cart_items
    get '/orders/complete', to: 'orders#complete'
    resources :orders
    post '/orders/confirm', to: 'orders#confirm'
  end

  namespace :admin do
    resources :homes
    resources :genres
    resources :items
    resources :customers
    resources :orders
  end

  root to: 'public/homes#top'

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def active_for_authentication?
    super && (is_active == true)
  end
  
  def full_address_current_customer
    '〒' + postal_code + ' ' + address + ' ' + last_name
  end

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy 
  has_many :orders, dependent: :destroy
  

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if
     @customer.update(customer_params)
     redirect_to admin_customers_path
    else
     @customer = Customer.find(params[:id])
     render :edit
    end
  end
  
  def check
    @customer = Customer.find(params[:id])
  end
  
  

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_active)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  
  def after_sign_up_path_for(_resource)
    customer_path(current_customer.id)
  end
  
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end


end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h1><%= @customer.last_name %>さんの会員情報編集</h1>

<%= form_with model: @customer, url: admin_customer_path(@customer.id), local:true do |f| %>
<table>
  <tbody>
    <tr>
      <td>名前</td>
      <td>
        <%= f.label :last_name,"（姓)" %>
        <%= f.text_field :last_name, autofocus: true %>
      </td>
      <td>
        <%= f.label :first_name,"(名)" %>
        <%= f.text_field :first_name, autofocus: true %>
      </td>
    </tr>
    <tr>
      <td>フリガナ</td>
      <td>
        <%= f.label :last_name_kana,"(セイ)" %>
        <%= f.text_field :last_name_kana, autofocus: true %>
      </td>
      <td>
        <%= f.label :first_name_kana,"(メイ)" %>
        <%= f.text_field :first_name_kana, autofocus: true %>
      </td>
    </tr>
    <tr>
      <td>郵便番号(ハイフンなし)</td>
      <td>
        <%= f.text_field :postal_code, autofocus: true %>
      </td>
    </tr>
    <tr>
      <td>住所</td>
      <td>
         <%= f.text_field :address, autofocus: true %>
      </td>
    </tr>
    <tr>
      <td>電話番号(ハイフンなし)</td>
      <td>
        <%= f.text_field :telephone_number, autofocus: true %>
      </td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td>
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </td>
    </tr>
     　<tr>
     　<td>会員ステータス</td>
    　  <td>
        <%= f.radio_button :is_active, TRUE  %>
    　　<%= f.label :is_active,  "有効" %>
    　  </td>
    　  <td>
    　　<%= f.radio_button :is_active, FALSE  %>
    　　<%= f.label :is_active,  "退会" %>
    　  </td>
    　</tr>
  </tbody>
</table>
<%= f.submit '変更を保存する' %>
<% end %>

app/views/admin/customers/index.html.erb
<h1>会員一覧</h1>
<table>
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
       <tr>
        <td><%= customer.id %></td>
        <td>
          <%= link_to admin_customer_path(customer.id) do %>
          <%= customer.last_name %><%= customer.first_name %>
          <% end %>
        </td>
        <td><%= customer.email %></td>
        <td>
          <% if customer.is_active == true %>
            有効
          <% else %>
            退会
          <% end %>
        </td>
       </tr>
      <% end %>
    </tbody>
 </table>

app/views/admin/customers/show.html.erb
<h1><%= @customer.last_name %>さんの会員詳細</h1>
<table>
  <tbody>
    <tr>
      <td>会員ID</td>
      <td><%= @customer.id %></td>
    </tr>
    <tr>
      <td>氏名</td>
      <td><%= @customer.last_name %></td>
      <td><%= @customer.first_name %></td>
    </tr>
    <tr>
      <td>フリガナ</td>
      <td><%= @customer.last_name_kana %></td>
      <td><%= @customer.first_name_kana %></td>
    </tr>
    <tr>
      <td>郵便番号</td>
      <td><%= @customer.postal_code %></td>
    </tr>
    <tr>
      <td>住所</td>
      <td><%= @customer.address %></td>
    </tr>
    <tr>
      <td>電話番号</td>
      <td><%= @customer.telephone_number %></td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td><%= @customer.email %></td>
    </tr>
    <tr>
      <td>会員ステータス</td>
      <td>
        <% if @customer.is_active == true %>
          有効
        <% else %>
          退会
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<%= link_to '編集する', edit_admin_customer_path(@customer.id) %>