config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

   delete '/cart_items/destroy_all', to: 'public/cart_items#destroy_all'

  scope module: :public do
    get '/homes/about', to: 'homes#about'
    resources :items
    get '/customers/check', to: 'customers#check'
    patch '/customers/check', to: 'customers#withdraw'
    resources :customers
    resources :addresses
    resources :cart_items
    get '/orders/complete', to: 'orders#complete'
    resources :orders
    post '/orders/confirm', to: 'orders#confirm'
  end

  namespace :admin do
    resources :homes
    resources :genres
    resources :items
    resources :customers
    resources :orders
  end

  root to: 'public/homes#top'

end

app/models/address.rb
class Address < ApplicationRecord
 validates :name, presence: true
 validates :address, presence: true
 validates :postal_code, presence: true
 
def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
end
 
 belongs_to :customer
 
end

app/models/admin.rb
class Admin < ApplicationRecord




  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def active_for_authentication?
    super && (is_active == true)
  end
  
  def full_address_current_customer
    '〒' + postal_code + ' ' + address + ' ' + last_name
  end

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy 
  has_many :orders, dependent: :destroy
  

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
  has_many :items, dependent: :destroy
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
 validates :name, presence: true
 validates :introduction, presence: true
 validates :price, presence: true
 belongs_to :genre
 has_many :cart_items, dependent: :destroy
 has_many :order_details, dependent: :destroy
 attachment :image
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  # 注文モデル
  enum payment_method: { credit_card: 0, transfer: 1 }
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)

    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end

  end

  def edit
    @genre = Genre.find(params[:id])

  end

  def update
    @genre = Genre.find(params[:id])
   if @genre.update(genre_params)
    redirect_to admin_genres_path
   else
    @genre = Genre.find(params[:id])
    render :edit
   end
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    redirect_to admin_genres_path
  end

    private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

def index
  @orders = Order.all.page(params[:page]).per(5)
  
end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
   @item = Item.new(item_params)
   if @item.save
      redirect_to admin_item_path(@item.id)
   else
      render :new
   end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
   @item = Item.find(params[:id])
    if @item.update(item_params)
     redirect_to admin_items_path
    else
     @item = Item.find(params[:id])
     render :edit
    end
  end

   def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to admin_items_path
   end

  private


  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

def show
  @order = Order.find(params[:id])
  @orders = @order.order_details
end
def index
end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
  

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/show_helper.rb
module Admin::ShowHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/create.html.erb
<h1>Admin::Genres#create</h1>
<p>Find me in app/views/admin/genres/create.html.erb</p>

app/views/admin/genres/edit.html.erb
<h1>ジャンル編集</h1>

<% if @genre.errors.any? %>
  <%= @genre.errors.count %>件のエラーが発生しました
  <% @genre.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_with model:@genre,url: admin_genre_path, local: true do |f| %>
<p>ジャンル名</p>
<%= f.text_field :name %>
<%= f.submit '保存を保存' %>
<% end %>

app/views/admin/genres/index.html.erb
<h1>ジャンル一覧・追加</h1>

<% if @genre.errors.any? %>
  <%= @genre.errors.count %>件のエラーが発生しました
  <% @genre.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<p>ジャンル名</p>
<%= form_with model:@genre, url: admin_genres_path, local:true do |f| %>
<%= f.text_field :name %>
<%= f.submit '新規作成' %>
<% end %>
<h1>ジャンル</h1>
<% @genres.each do |genre| %>
<%= genre.name %>
<p><%= link_to "編集する", edit_admin_genre_path(genre) %></p>
<p><%= link_to "削除する", admin_genre_path(genre), method: :delete %></p>
<% end %>

app/views/admin/genres/update.html.erb
<h1>Admin::Genres#update</h1>
<p>Find me in app/views/admin/genres/update.html.erb</p>

app/views/admin/homes/index.html.erb
<h1>注文履歴一覧</h1>
<table class="table table-bordered col-lg-7 mx-auto">
    <thead class="table-secondary">
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
      </tr>
    </thead>
     <tbody>
   　　 <% @orders.each do |order| %>
       <tr>
        <td>
          <%= link_to order.created_at, admin_order_path(order.id) %>
        </td>
        <td>
        <%= order.customer.last_name %>
 　　　　　<%= order.customer.first_name %>
 　　　　　</td>
        <td>
        <%= order.order_details.all.sum(:amount) %>
        </td>
       </tr>
      <% end %>
    </tbody>
 </table>
 <span><%= paginate @orders %></span>

app/views/admin/items/edit.html.erb
<h1>商品編集</h1>
<%= form_with model: @item, url: admin_item_path(@item.id), local:true do |f| %>
  <table>
    <tbody>
      <tr>
       <td>商品画像</td>
       <td><%= f.attachment_field :image %>
       </td>
      </tr>
      <tr>
       <td>商品名</td>
       <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <td>商品説明</td>
        <td><%= f.text_area :introduction %></td>
      </tr>
      <tr>
        <td>ジャンル</td>
        <td><%= f.select :genre_id, Genre.all.map { |genre| [genre.name, genre.id] } %></td>
      </tr>
      <tr>
        <td>税込価格<br>税抜き価格</td>
        <td><%= f.text_field :price %>円</td>
      </tr>
    　<tr>
    　  <td>
        <%= f.radio_button :is_active, TRUE  %>
    　　<%= f.label :is_active,  "販売中" %>
    　  </td>
    　  <td>
    　　<%= f.radio_button :is_active, FALSE  %>
    　　<%= f.label :is_active,  "販売停止中" %>
    　  </td>
    　</tr>
    </tbody>
  </table>
<%= f.submit '更新' %>
<% end %>

app/views/admin/items/index.html.erb
<h1>商品一覧</h1>
<h2><%= link_to "商品追加", new_admin_item_path %></h2>
<table>
    <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
       <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admin_item_path(item.id) %></td>
        <td><%= item.price %>円</td>
        <td><%= item.genre.name %></td>
        <td>
          <% if item.is_active == true %>
            販売中
          <% else %>
            販売停止中
          <% end %>
        </td>
       </tr>
      <% end %>
    </tbody>
 </table>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>
<%= form_with model: @item, url: admin_items_path, local:true do |f| %>
  <table>
    <tbody>
      <tr>
       <td>商品画像</td>
       <td><%= f.attachment_field :image %></td>
      </tr>
      <tr>
       <td>商品名</td>
       <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <td>商品説明</td>
        <td><%= f.text_area :introduction %></td>
      </tr>
      <tr>
        <td>ジャンル</td>
        <td><%= f.select :genre_id, Genre.all.map { |genre| [genre.name, genre.id] } %></td>
      </tr>
      <tr>
        <td>税抜価格</td>
        <td><%= f.text_field :price %>円</td>
      </tr>
    　<tr>
    　  <td>
        <%= f.radio_button :is_active, TRUE  %>
    　　<%= f.label :is_active,  "販売中" %>
    　  </td>
    　  <td>
    　　<%= f.radio_button :is_active, FALSE  %>
    　　<%= f.label :is_active,  "販売停止中" %>
    　  </td>
    　</tr>
    </tbody>
  </table>
<%= f.submit '新規登録' %>
<% end %>

app/views/admin/items/show.html.erb
<h1>商品詳細</h1>
<%= attachment_image_tag @item, :image, :fill, 225, 225 %>
<table>
 <tbody>
  <tr>
   <td>商品名</td>
   <td><%= @item.name %></td>
  </tr>
  <tr>
   <td>商品説明</td>
   <td><%= @item.introduction %></td>
  </tr>
  <tr>
   <td>ジャンル</td>
   <td><%= @item.genre.name %></td>
  </tr>
  <tr>
   <td>税込価格（税抜き価格）</td>
   <td><%= (@item.price*1.1).round(0) %>円(<%= @item.price %>円)</td>
  </tr>
  <tr>
   <td>販売ステータス</td>
   <td> <% if @item.is_active == true %>
         販売中
        <% else %>
         販売停止中
        <% end %>
    </td>
  </tr>
 </tbody>
</table>
<%= link_to  "編集する", edit_admin_item_path %>
<%= link_to "削除する", admin_item_path(@item.id), method: :delete %>

app/views/admin/orders/show.html.erb
<h1>商品詳細</h1>
<table>
  <tbody>
    <tr>
      <td>購入者</td>
      <td><%= @order.customer.last_name %> <%= @order.customer.first_name %></td>
    </tr>
     <tr>
      <td>注文日</td>
      <td><%= @order.created_at %></td>
    </tr>
     <tr>
      <td>配送先</td>
      <td><%= @order.address %></td>
    </tr>
     <tr>
      <td>支払い方法</td>
      <td><%= @order.payment_method_i18n %></td>
    </tr>
  </tbody>
</table>

<h2>注文情報確認</h2>
<table class="table table-bordered col-lg-8 ">
<thead class="table-secondary">
 <tr>
   <th>商品名</th>
   <th>単価(税込)</th>
   <th>個数</th>
   <th>小計</th>
 </tr>
</thead>

 <tbody>
 <% @sum = 0 %>
 <% @orders.each do |order_detail| %>
  <tr>
    <td><%= order_detail.item.name %></td>
    <td><%= order_detail.item.price %></td>
    <td><%= order_detail.amount %></td>
    <td><%= order_detail.item.price * order_detail.amount %></td>
    <% @sum += (order_detail.item.price * order_detail.amount) %>
  </tr>
  <% end %>
 </tbody>
</table>

<table>
 <tbody>
  <tr>
   <td>商品合計</td>
   <td><%= @sum %></td>
  </tr>
  <tr>
   <td>送料</td>
   <td><%= @order.shipping_cost %></td>
  </tr>
  <tr>
   <td>請求金額合計</td>
   <td><%= @order.total_payment %></td>
  </tr>
 </tbody>
</table>