config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

   delete '/cart_items/destroy_all', to: 'public/cart_items#destroy_all'

  scope module: :public do
    get '/homes/about', to: 'homes#about'
    resources :items
    get '/customers/check', to: 'customers#check'
    patch '/customers/check', to: 'customers#withdraw'
    resources :customers
    resources :addresses
    resources :cart_items
    get '/orders/complete', to: 'orders#complete'
    resources :orders
    post '/orders/confirm', to: 'orders#confirm'
  end

  namespace :admin do
    resources :homes
    resources :genres
    resources :items
    resources :customers
    resources :orders
  end

  root to: 'public/homes#top'

end

app/models/address.rb
class Address < ApplicationRecord
 validates :name, presence: true
 validates :address, presence: true
 validates :postal_code, presence: true
 
def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
end
 
 belongs_to :customer
 
end

app/models/admin.rb
class Admin < ApplicationRecord




  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def active_for_authentication?
    super && (is_active == true)
  end
  
  def full_address_current_customer
    '〒' + postal_code + ' ' + address + ' ' + last_name
  end

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy 
  has_many :orders, dependent: :destroy
  

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
  has_many :items, dependent: :destroy
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
 validates :name, presence: true
 validates :introduction, presence: true
 validates :price, presence: true
 belongs_to :genre
 has_many :cart_items, dependent: :destroy
 has_many :order_details, dependent: :destroy
 attachment :image
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  # 注文モデル
  enum payment_method: { credit_card: 0, transfer: 1 }
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

def index
  @orders = Order.all.page(params[:page]).per(5)
  
end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
   @item = Item.new(item_params)
   if @item.save
      redirect_to admin_item_path(@item.id)
   else
      render :new
   end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
   @item = Item.find(params[:id])
    if @item.update(item_params)
     redirect_to admin_items_path
    else
     @item = Item.find(params[:id])
     render :edit
    end
  end

   def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to admin_items_path
   end

  private


  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
  

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/show_helper.rb
module Admin::ShowHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

 <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  </head>

  <body>

  <header class="shadow-sm">
    <nav class="navbar navbar-expand-lg navbar-light">

      <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
          </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">

      <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <li class="m-2 nav-item">
              <%= link_to "商品一覧", admin_items_path, class: 'border rounded nav-link text-dark' %>
            </li>
            <li class="m-2 nav-item">
              <%= link_to "会員一覧", admin_customers_path,class: 'border rounded nav-link text-dark' %>
            </li>
            <li class="m-2 nav-item">
              <%= link_to "注文履歴一覧", admin_homes_path, class: 'border rounded nav-link text-dark' %>
            </li>
             <li class="m-2 nav-item">
              <%= link_to "ジャンル一覧", admin_genres_path, class: 'border rounded nav-link text-dark' %>
            </li>
            <li class="m-2 nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'border rounded nav-link text-dark' %>
            </li>
          <% elsif customer_signed_in? %>
            <li class="m-2 nav-item">
              <%= link_to "マイページ",customer_path(current_customer.id), class: 'border rounded nav-link text-dark' %>
            </li>
            <li class="m-2 nav-item">
              <%= link_to "商品一覧",items_path, class: 'border rounded nav-link text-dark' %>
            </li>
            <li class="m-2 nav-item">
              <%= link_to "カート", cart_items_path, class: 'border rounded nav-link text-dark' %>
            </li>
            <li class="m-2 nav-item">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'border rounded nav-link text-dark' %>
            </li>
          <% else %>
            <li class="m-2 nav-item">
              <%= link_to "About", homes_about_path, class: 'border rounded nav-link text-dark' %>
            </li>
            <li class="m-2 nav-item">
              <%= link_to "商品一覧",items_path, class: 'border rounded nav-link text-dark' %>
            </li>
            <li class="m-2 nav-item">
              <%= link_to "新規登録", new_customer_registration_path, class: 'border rounded nav-link text-dark' %>
            </li>
            <li class="m-2 nav-item">
              <%= link_to "ログイン", new_customer_session_path, class: 'border rounded nav-link text-dark' %>
            </li>
          <% end %>
         </ul>
        </div>
      </div>
    </nav>
  </header>

  <main>
    <%= yield %>
  </main>

  <footer class="shadow-sm">
  </footer>

  </body>
</html>